### ISSUE TITLE
当前 KookBC 的 stop 命令在命令行里需要使用两次才能彻底结束

### ISSUE THREAD

**Issue by xiaoACE6716** [SNWCreations/KookBC#112]
## 您期望得到什么

一次 stop 命令执行完毕后应该彻底关闭

## 实际得到什么

第一次 stop执行完之后 虽然机器人已下线，但进程未完全结束。
从附带的日志里可以看出，第一次 stop 后，卸载了插件 机器人也下线了，但是进程还在
直到第二次使用 stop 后，进程才彻底关闭

## 报错日志

https://pastebin.ubuntu.com/p/gdDdNMvKbk/

## 相关信息

  - KookBC 版本: 0.32.1
  - JKook API 版本: 0.54.0
  - Java 版本: Java 8

**Comment by huanmeng-qwq** [comment]
未能复现，重复stop指令时并不会触发二次shutdown，可能是其它插件关闭需要一定的时间导致的视觉错误。

**Comment by xiaoACE6716** [comment]
> 未能复现，重复stop指令时并不会触发二次shutdown(会打印日志`The client has already stopped`在debug中)，可能是其它插件关闭需要一定的时间导致的视觉错误。

https://pastebin.ubuntu.com/p/zY8bDyx5hH/ 没有任何插件时，也一样
