### ISSUE TITLE
ImageElement

### ISSUE THREAD

**Issue by RedCarl** [SNWCreations/KookBC#15]
## 您期望得到什么
ImageElement的circle
让图片变成圆形

## 实际得到什么
并没有效果，还是方的

## 重现错误的步骤

                                new ImageElement(
                                        user.getAvatarUrl(true),
                                        user.getName(),
                                        true
                                ),

## 相关信息

  - KookBC 版本: 最新
  - JKook API 版本: 最新
  - 您使用的 Bot 的相关信息 (如 名称、作者、版本): 卡尔酱
  - Java 版本: 8
  - 操作系统 (及其版本): macos 13

**Comment by SNWCreations** [comment]
收到。稍后处理。

**Comment by SNWCreations** [comment]
应当已修复，请关注 0.26.10 ，马上发布。

**Comment by SNWCreations** [comment]
请使用 0.26.11 而不是 0.26.10 以检查问题是否修复。

**Comment by huanmeng-qwq** [comment]
经测试已正确修复
