### ISSUE TITLE
accessory与accessory Mode 应该是Nullable的

### ISSUE THREAD

**Issue by xiaoACE6716** [SNWCreations/KookBC#17]
## 您期望得到什么
在SectionModule里传入的accessory与accessory Mode 应该是Nullable的

## 实际得到什么
但是它报错了
https://paste.ubuntu.com/p/8pmGptF4WT/

## 重现错误的步骤

  new new SectionModule(new Paragraph(3, Arrays.asList(some MarkdownElement......)), null, null))

## 相关信息

  - KookBC 版本:0.26.11
  - JKook API 版本:0.48.2
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本):
  - Java 版本:Java 8
  - 操作系统 (及其版本):Windows 10

**Comment by SNWCreations** [comment]
应当在 0.26.12 中修复。请测试。

**Comment by xiaoACE6716** [comment]
经测试已正确修复
