### ISSUE TITLE
找不到类，但是出现了NullPointerException

### ISSUE THREAD

**Issue by SNWCreations** [SNWCreations/KookBC#26]
这个问题不是在我的设备上发生的，它原本由社区成员 Mores.#3552 提交。

## 您期望得到什么

在找不到类时直接抛出 ClassNotFoundException 。

## 实际得到什么

抛出了 ClassNotFoundException ，但是其最终原因是操作值为 null 的 byte[] 导致的 NullPointerException

## 重现错误的步骤

初步分析得:

在一个 JKook 插件中调用一个不存在于 KookBC 而插件本身又未打包的第三方库方法即可触发。

## 报错日志

https://img.kookapp.cn/assets/2023-03/oifoEduGiw0tq0fy.png

## 相关信息

  - KookBC 版本: 0.26.13
  - JKook API 版本: 0.48.2
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本): 未知
  - Java 版本: 未知
  - 操作系统 (及其版本): 未知

此异常存在于 Mixin 支持的相关代码中，故指派 @huanmeng-qwq 处理。

**Comment by SNWCreations** [comment]
https://github.com/SNWCreations/KookBC/blob/main/src/main/java/snw/kookbc/impl/launch/LaunchClassLoader.java#L209
报错日志指向这行，即使 fail runTransformer 也出现了npe，分析可知 classBytes 已经是 null 。
修改建议: 在 getClassBytes 方法下一行立刻进行 not null 检查，如果 is null，抛出 ClassNotFoundException 。

**Comment by huanmeng-qwq** [comment]
#27
