### ISSUE TITLE
KookBC 在调用 com/sun/jna/platform/win32/Kernel32 发生 NoClassDefFoundError

### ISSUE THREAD

**Issue by RealSeek** [SNWCreations/KookBC#31]
## 您期望得到什么

返回 Process 的 pid

## 实际得到什么

NoClassDefFoundError

## 重现错误的步骤

  更换到 KookBC 0.27.0 版本启动调用此方法就会报错
  经过测试使用旧版本的 KookBC 0.26.8 并不会报错

## 报错日志

![image](https://img.kookapp.cn/assets/2023-04/9HIkdR4N9u0y409j.png)

## 相关信息

  - KookBC 版本: 0.27.0
  - JKook API 版本: 3e89cde
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本):
  - Java 版本: 8
  - 操作系统 (及其版本): Windows 10 专业工作站版 22H2

**Comment by SNWCreations** [comment]
已修复，在你的插件工程的资源文件夹下添加一个名为 "KBC_CLSLDR_INCLUDE" 的文件，内容为:
```
com.sun.jna.
```
然后再编译你的插件（注意确认你的最终工件有 KBC_CLSLDR_INCLUDE 文件），去运行，问题应当已修复。
若确定已修复，关闭此 Issue 即可，若仍未修复，将新的报错日志提交到这里即可。

**Comment by SNWCreations** [comment]
已由 Issue 发布者在 KOOK 确定完全修复。
