### ISSUE TITLE
使用 Cloud 注册命令报错无法正常返回

### ISSUE THREAD

**Issue by RealSeek** [SNWCreations/KookBC#64]
## 您期望得到什么
详细的错误堆栈信息

## 实际得到什么
无

## 重现错误的步骤

  1.使用 Cloud 注册一个指令
  2.产生报错

## 报错日志
无

## 相关信息

  - KookBC 版本: 0.27.5
  - JKook API 版本: 0.49.2
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本):
  - Java 版本: 11
  - 操作系统 (及其版本): windows 10

**Comment by RealSeek** [comment]
@huanmeng-qwq

**Comment by huanmeng-qwq** [comment]
可以使用litecommand分支的最新构建版本使用litecommands框架开发，cloud框架将在未来移除。详情参阅[这里](https://github.com/SNWCreations/KookBC/blob/litecommand/CLOUD_MIGRATE_TO_LITECOMMANDS.md)
