### ISSUE TITLE
当机器人加入的服务器数量过多，会有 HTTP 堵塞导致的性能问题

### ISSUE THREAD

**Issue by RealSeek** [SNWCreations/KookBC#73]

**Comment by xiaoACE6716** [comment]
目前个人有想法把所有东西都改成  lazy-load mode 参考https://github.com/SNWCreations/KookBC/commit/9db008043110752ca10cb46a77b03e8ef1a1934a

**Comment by SNWCreations** [comment]
正在重启对这个问题的解决过程，正在参考已被破坏的 #75 继续此问题的修复工作。

**Comment by SNWCreations** [comment]
我们从 d1471db6618f9f3172f8c6d1d4b1bc95ad3187d3 开始。

**Comment by SNWCreations** [comment]
try https://github.com/SNWCreations/KookBC/actions/runs/9412498787

**Comment by SNWCreations** [comment]
Resolved by version 0.31.0, fixed by #94, #100
