### ISSUE TITLE
LiteCommand的@Prefix注解不完全生效

### ISSUE THREAD

**Issue by xiaoACE6716** [SNWCreations/KookBC#89]
![847697271b9e4a0b6ee4bf64674ea060](https://github.com/user-attachments/assets/158c587d-917c-4363-8861-ef7dc6690beb)
![1b021dd5e52ef658a89c36ca97e4d449](https://github.com/user-attachments/assets/24ee3ca2-7356-4edc-a232-18ed5b159974)
![07a014f8d73608e9ba22dd57b968568d](https://github.com/user-attachments/assets/f4636df3-9dfc-48f2-864e-6a1ebdef987f)
如图所示，@Prefix注解只在第一个命令中生效了

**Comment by huanmeng-qwq** [comment]
未能成功复现，不知道还有没有更详细的步骤? @xiaoACE6716

**Comment by xiaoACE6716** [comment]
具体代码如下
https://pastebin.ubuntu.com/p/gnyc7fVTSd/
https://pastebin.ubuntu.com/p/BX3qzmrJjC/ 
在Main类中注册
` LiteKookFactory.builder(this).commands(new VerifyCommand()).commands(new AddKeyCommand())build();`
bot启动后日志也没有报错，而/help指令中显示如上面的图一样，用/addkey 能正确响应

**Comment by huanmeng-qwq** [comment]
已定位到错误位置目前可以使用下面的代码解决:
```java
 LiteKookFactory.builder(this).commands(new VerifyCommand(), new AddKeyCommand()).build();
```
