### ISSUE TITLE
在 kbc.yml 添加一个配置项，修改 Bucket 的日志等级，便于加入服务器数量多的 Bot 排查性能问题

### ISSUE THREAD

**Issue by RealSeek** [SNWCreations/KookBC#96]
## 您理解并明白，您确认此 Issue 符合下列要求:

1. 请求添加的功能是为了增强 **KookBC** 的能力，如可配置性。
2. 请求添加的功能 **不是对 JKook API 的功能扩充** ，如果是，请到 [JKook 仓库](https://github.com/SNWCreations/JKook) 提交 Issue ，而不是在这里提交。
3. 当您的 Issue 不满足上述要求或有其他合理原因时，您的 Issue 将被关闭。

## 您期望添加什么

通过 kbc.yml 添加一个选项修改日志等级

[Bucket.java](https://github.com/SNWCreations/KookBC/blob/be7fdd6403d7f40d981ab51f4819443edfca32ef/src/main/java/snw/kookbc/impl/network/Bucket.java#L65)

**Comment by xiaoACE6716** [comment]
in the works

**Comment by SNWCreations** [comment]
Done
