### ISSUE TITLE
希望修改 KookBC 自带的 help 翻页菜单样式

### ISSUE THREAD

**Issue by RealSeek** [SNWCreations/KookBC#97]
## 您理解并明白，您确认此 Issue 符合下列要求:

1. 请求添加的功能是为了增强 **KookBC** 的能力，如可配置性。
2. 请求添加的功能 **不是对 JKook API 的功能扩充** ，如果是，请到 [JKook 仓库](https://github.com/SNWCreations/JKook) 提交 Issue ，而不是在这里提交。
3. 当您的 Issue 不满足上述要求或有其他合理原因时，您的 Issue 将被关闭。

## 您期望添加什么

Litecommands 注册别名会让翻页菜单反直觉

## 设计思路

我觉得可以修改成这样，更符合阅读习惯

![3ce3dfa38d6a22759282d3db43639d69](https://github.com/user-attachments/assets/a1fcabf2-9a27-42db-adb7-5868af0e1013)

**Comment by huanmeng-qwq** [comment]
已在feat/97分支实现litecommands别名的注册区分，help排版格式的话你可以直接修改提交上去 @RealSeek

**Comment by RealSeek** [comment]
另外可以考虑修改一下注册命令的顺序么，现在是乱序的，如果我想按照特定顺序注册命令
让常用命令在前，是否会更好？

**Comment by huanmeng-qwq** [comment]
> 另外可以考虑修改一下注册命令的顺序么，现在是乱序的，如果我想按照特定顺序注册命令 让常用命令在前，是否会更好？

请前往[litecommands](https://github.com/Rollczi/LiteCommands/issues/new)仓库提交issue，可能是CommandMerger#commandsByName,commands 为HashMap导致的
